---
title: Getting Started with the micro:bit
hero_image: images/banner.png
description: Learn how to push programs to your micro:bit using a Raspberry Pi
original_url: https://raspberrypi.org/learning/getting-started-with-microbit
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: microbit, pyton
site_areas: projects
hardware: microbit
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Getting started with the micro:bit
- title: Starting mu
- title: Plugging in your micro:bit
- title: Using mu
- title: Using the REPL
- title: Writing and pushing code
  completion: internal
- title: More features of the micro:bit
- title: What next?
